### ISSUE TITLE
exporting not filtering out views

### ISSUE THREAD

**Issue by ardydo** [aardappel/procrastitracker#1]
I have tried to export out views from the db but it seem to not work. I'm trying to export from a date forward becaus I want to discard data from before a set date but i'm unable to.

I set it to a starting date -> today and then export, remove the old db and then open the application and the db is empty as expected. But when I import the view, it does import the whole old db. I have tried restarting the pc, terminating the app and everything else that there is to make this work, but it always merge the old db whole. Maybe it is ignoring views when exporting? It's odd because when I export to html it does show only the filtered data...

Am I doing something wrong?

**Comment by aardappel** [comment]
No, I just tried this, and even though it only saves the tree nodes for which there was an entry today, it looks like there's a bug in `node::save` whereby it saves the day data for the whole range of dates regardless.

**Comment by ardydo** [comment]
I see. Is there any workaround this issue? Like editing the database itself? If so, what would I need to do so?

**Comment by aardappel** [comment]
Just had a look and seems like I fixed it. Was able to export a view and load it back in with exact same timings.

**Comment by aardappel** [comment]
https://github.com/aardappel/procrastitracker/commit/7ab1c589fc1a270a1ae9f44547c92179b884cef0

**Comment by ardydo** [comment]
Oh yes! It's fixed! Thank you very much!
