### ISSUE TITLE
feature request: application protection

### ISSUE THREAD

**Issue by macarthor** [aardappel/procrastitracker#100]
would you please add some features like application protection/lock, as means only authorized people can open the application and read the data, for any reasons

**Comment by aardappel** [comment]
Not planned.
If you need to protect your computer against other users, there is probably specialized software for that.

**Comment by macarthor** [comment]
> Not planned. If you need to protect your computer against other users, there is probably specialized software for that.

hi aardappel,

no i don't wanna protect my pc from others. on the contrary, this PC is for my kid to take online lessions. i use your great application to track his usage, and keep him from clearing the tracking result...
