### ISSUE TITLE
Wrong app name

### ISSUE THREAD

**Issue by shumafuk** [aardappel/procrastitracker#103]
In log I have "msedgewebview2" that contains Photoshop and projects opened in Photoshop (psd, png, jpg...). Is it bug? Can I somehow rename process in log view? Thanks.

**Comment by aardappel** [comment]
That is unlikely a bug.. its the windows default web browser engine, and it likely at some point showed you some files, maybe from explorer or so.

There is no rename. This is what MS likes to call it, and if it gets used again, that is the name under which new data would get added, so renaming would not be helpful.

**Comment by shumafuk** [comment]
Hm, it could be related to preview in explorer, which would explain those names. Thanks.
