### ISSUE TITLE
Away time tracker pops under other windows

### ISSUE THREAD

**Issue by rogierg** [aardappel/procrastitracker#11]
I have been using procrastitracker a couple of years now and only now have I had a need for the away tracker :-). (Great tool by the way, many thanks)

The problem is that this window pops "under" other windows and thus I only notice it when alt-tabbing to other stuff. Running on Windows 7, 64bit. If you need any other info let me know.

**Comment by aardappel** [comment]
That's indeed unfortunate. I seem to remember trying to force them to pop on top, but not succeeding.

**Comment by maximemousserin** [comment]
Hi, SetWindowPos did the trick for me #12

**Comment by aardappel** [comment]
Thanks for fixing this :)
