### ISSUE TITLE
The latest version is identified as Trojan: Win32/Maltule.C!cl by Windows Defender.

### ISSUE THREAD

**Issue by kemiisto** [aardappel/procrastitracker#14]
Both the setup package and the installed executable are identified as [Trojan: Win32/Maltule.C!cl](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fMaltule.C!cl&threatid=2147709295&enterprise=0) by Windows Defender at Windows 10.

Items for the setup package: 

> containerfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy\{6C164890-F6A4-465B-B279-F18934AA2393}-ProcrastiTracker_Setup.exe
> containerfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\3573A51A-0626-6640-3937-50EF4FCE2F86_1d1ebcda759762d
> containerfile:C:\Users\wildcat\Downloads\ProcrastiTracker_Setup.exe
> file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy\{6C164890-F6A4-465B-B279-F18934AA2393}-ProcrastiTracker_Setup.exe->(nsis-6-procrastitracker.exe)
> file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\3573A51A-0626-6640-3937-50EF4FCE2F86_1d1ebcda759762d
> file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\3573A51A-0626-6640-3937-50EF4FCE2F86_1d1ebcda759762d->(nsis-6-procrastitracker.exe)
> file:C:\Users\wildcat\Downloads\ProcrastiTracker_Setup.exe->(nsis-6-procrastitracker.exe)
> webfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy\{6C164890-F6A4-465B-B279-F18934AA2393}-ProcrastiTracker_Setup.exe|chrome.exe
> webfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\3573A51A-0626-6640-3937-50EF4FCE2F86_1d1ebcda759762d|http://strlen.com/procrastitracker/ProcrastiTracker_Setup.exe|chrome.exe
> webfile:C:\Users\wildcat\Downloads\ProcrastiTracker_Setup.exe|http://strlen.com/procrastitracker/ProcrastiTracker_Setup.exe|chrome.exe

Items for the installed executable: 

> file:C:\Program Files (x86)\ProcrastiTracker\procrastitracker.exe
> file:C:\Users\wildcat\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ProcrastiTracker.lnk
> process:pid:8640,ProcessStart:131144269884830321
> startup:C:\Users\wildcat\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ProcrastiTracker.lnk

**Comment by aardappel** [comment]
Thanks! Just tested and indeed I get the same error.

I upgraded my version of NSIS (the installer software) and now Windows Defender doesn't find a virus anymore.. please try again.
