### ISSUE TITLE
Buttons on left side don't appear on low res screen/displays [720p]

### ISSUE THREAD

**Issue by saifali96** [aardappel/procrastitracker#17]
Hi! I love the work you are doing. I wanted to tell you that I'm not able to view the "apply tag to node" and "rename tag" button on my laptop screen, it's HD 720p, even on full screen.
You should embed a scroll on the left side.
Thanks :)

**Comment by aardappel** [comment]
Just made a quick fix whereby I put those buttons above the tag list rather than beneath. That isn't a perfect fix, but should help for the moment.

**Comment by saifali96** [comment]
@aardappel thanks, that would do for the moment.
BTW thank you so much for this software! really helps entrepreneurs like me work rather than procrastinate or at least helps in making a good proportion! 👍 
Anyway you can close the issue if you want to now, thanks for the quick fix again.

**Comment by aardappel** [comment]
good to hear :)
