### ISSUE TITLE
Feature request - tree view multiselect with ctrl or shift

### ISSUE THREAD

**Issue by scanzy** [aardappel/procrastitracker#21]
Tree view multiselect with ctrl or shift to use "apply tag" with multiple nodes in one click

I know it may be difficult to implement since everything is written with Win32 api, but I think it would be soo useful

**Comment by aardappel** [comment]
Agree that would be super useful..

**Comment by aardappel** [comment]
Just had a look what's involved, and doesn't look like the standard WIN32 TreeView supports multi-select. It did in Vista apparently, but was removed again. You can simulate the effect with checkboxes, but that's not as nice. Or link in a complete custom control.

Then it would need an overhaul over some of the other UI, which currently assumes single selections.

I am not sure if it makes sense to add this, it be better to at some point invest the time to redo the entire UI using a more modern system.

**Comment by aardappel** [comment]
As a compromise, I just added a keyboard shortcut for "Apply Tag To Node" which is `T`. This should at least speed up tagging multiple nodes a little.

**Comment by scanzy** [comment]
Wow! Good job, I think this is even mroe useful :D
