### ISSUE TITLE
Pressed H by accident, root node disappeared, can't get it back

### ISSUE THREAD

**Issue by chylex** [aardappel/procrastitracker#29]
Got it back by making a custom build that discards the 'hidden' field in nodes, but it should probably be fixed or made more clear as to how to solve this..

**Comment by aardappel** [comment]
Do you have an older version of TreeSheets? In the current version it is CTRL+H, exactly to make accidental use harder :)

To unhide is CTRL+U (or U in your version), but I guess you have an empty treeview now?

I shall add a check to not allow the root to be hidden. I can also add a check that if the root is hidden to automatically unhide it, which should solve your problem?

**Comment by chylex** [comment]
U didn't work, because the treeview is empty so there's nothing to focus. Adding a check for a hidden root node could be useful, though I already built a custom version from source so it might not be needed unless someone else ran into the issue. Thanks for the quick response.

**Comment by aardappel** [comment]
Hmm, just tested, but with the current code, it is already impossible to hide the root node. I tried and wasn't able to hide it. The code specifically does `if (selectednode != root) {`.. so I'm not sure now how you managed to hide it, unless it was a really old version.

**Comment by chylex** [comment]
Hm, I've had it running for some time and I don't think I ever checked for updates, so that'd be the case. Sorry for the confusion.
