### ISSUE TITLE
Unintentionally 2 changes made by 1 pull request (no problem, but for information)

### ISSUE THREAD

**Issue by jt-fuw** [aardappel/procrastitracker#32]
Hello. I prepared 2 changes today: 1st was saving database when the procrastitracker is ended due to logout/reboot/shutdown, 2nd was Makefile changes for using NSIS (it modifies executable file name to match this needed by NSIS, and shows an information how to use NSIS to make an installer.

I put the 1st on the GitHub, made a pull request, and then put the 2nd, assuming the pull request will not be affected by the 2nd change - seems it was, and both changes were merged. This will not be a problem for anyone using MS compiler, as it ignores the Makefile; it should not be a problem for anyone using Mingw, as the 'make' will just tell that the NSIS can be used and how.

The only wrong thing is that the change title does not reflect fully what in fact was changed and this may be misguiding for anyone looking at history of changes.

**Comment by aardappel** [comment]
Ah.. yes I saw they were potentially unrelated changes. I don't think it's a big deal, as the total amount of people using this code right now is low.
