### ISSUE TITLE
time in Visual Studio is tracked as "away" time

### ISSUE THREAD

**Issue by zerobotix** [aardappel/procrastitracker#33]
Recently I noticed that procrastitracker shows me "away popup" when I switch focus from Visual Studio window to any another app. I use windows 10 with latest updates and run Visual Studio Enterprise 2015 Update 3 as administrator. What may cause this issue? Can I fix it from my side?

**Comment by aardappel** [comment]
Well, I'm on Windows 10 too, and also use Visual Studio (also 2015 until recently). Never seen anything like it. You mean to say to press on any other app in the task bar and it instantly comes up?

First, the away popup is by default off, so you must have turned it on. You can turn it off again in the settings.

It should only come up if it has detected you as idle for longer than 3 minutes (configurable in the settings also). Maybe somehow its not getting keyboard/mouse activity while in VS? But again, I haven't seen this, so it may be something specific to your computer. Do you have any tools/utilities that could affect mouse/keyboard? Any particular mouse/keyboard brand that comes with a fancy config tool?

**Comment by zerobotix** [comment]
Yes, I turned on this popup, and sometimes when I switch to another app using taskbar or alt+tab it comes up saying that I was idle for 3+ minutes. I just have catched it right now when I was working actively in the Photoshop CS6 app more than 3 minutes. Photoshop opens 2 tabs on the taskbar, one for the main application and another for window with photo. I see that PT has tracked 1 minute for this window with photo. I use ordinary a4tech keyboard and logitech mouse out-of-the-box without any configuration. I also experienced this issue in the past on my home laptop with windows 10 (anniversary update), but i just disabled PT there. It used to work fine on my work PC one month ago, so I believe the reason of this issue is windows updates. I will update you if I collect more details.

**Comment by aardappel** [comment]
Ok, figured it out: the problem is that you're running it in administrator mode. Procrastitracker being an unprivileged app cannot monitor it.

There's 2 solutions:
- Stop running VS as admin (why do you need this?)
- Also run Procrastitracker as admin. I tried this out, and it works, got no popup anymore from VS (in admin mode).

**Comment by aardappel** [comment]
This appears related: https://stackoverflow.com/questions/15898769/how-to-receive-keyboard-input-from-application-with-admin-privileges-to-a-non-ad

**Comment by zerobotix** [comment]
Thanks, running PT as admin works for me. I always run VS as admin, because it doesn't allow me to debug without admin privileges. 

Thanks for your help and for awesome app!
