### ISSUE TITLE
Can't detect LOL application when gaming.

### ISSUE THREAD

**Issue by lj8385174** [aardappel/procrastitracker#43]
I don't whether it is the full screen mode to cause this problem, it seems that it can't detect the lol application.

**Comment by aardappel** [comment]
Yeah, I've seen that with a few games, and I am not sure what these games do differently that makes them appear not active.

**Comment by lj8385174** [comment]
I guess I find the problem. Some game have the ability to mask some specific keys. For example, LOL will mask all the a-z characters. I guess this is some anti-cheat mechanism. I run the procrastitracker as administrator, it seems detect all the keys

**Comment by lj8385174** [comment]
So I think other games have the same mechanisms, and run as admin should be work

**Comment by lj8385174** [comment]
However, the latest version of proc...tracker is readily to deal with it, cause LOL always run as full-screen which will never has idle states, lol.

**Comment by aardappel** [comment]
Ah good to know.. glad the FS feature helps, thanks @nuzayets :)
