### ISSUE TITLE
Update Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [aardappel/procrastitracker#52]
Dear @aardappel,
the repository is updated with commits which bring features and fixes, yet the official binary version is still dated back to 2016. Perhaps it’s very time to release a new version for mere Windows users without compiler? Releases section of Github might be the very place for it.

**Comment by aardappel** [comment]
Updated the binary on http://strlen.com/procrastitracker/

I could use the releases page, but then again most users are not necessarily programmers, so github is even more foreign to them than my page :)

I guess most commits since then have been small features so hadn't thought of updating it.

**Comment by sergeevabc** [comment]
Cannot launch the app after updating.

![](https://images.vfl.ru/ii/1547847399/6f0efc6d/25011857.png)

**Comment by aardappel** [comment]
Are you on Windows 7?

**Comment by aardappel** [comment]
Looks like we gained a dependency on Xinput in this recent contribution: https://github.com/aardappel/procrastitracker/commit/43c26288b2bb3ce193eb0aae21a10eda6c6398c8

**Comment by sergeevabc** [comment]
Windows 7 x64, indeed.

**Comment by aardappel** [comment]
Linking against a different version of Xinput that is supposed to be Windows 7 compatible: https://github.com/aardappel/procrastitracker/commit/7d57768de4ab734b5548a7278ed3d572cd8a0bc4

(and once more updated exe :)

**Comment by sergeevabc** [comment]
Alright, it launches without a flaw now. Thank you, @aardappel.
