### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by hkclark** [aardappel/procrastitracker#56]
I just installed "ProcrastiTracker_Setup.exe" from http://strlen.com/procrastitracker/#download and Windows Defender is reporting: 

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fBearfoos.A!ml&threatid=2147731250.  

"ProcrastiTracker_Setup.exe" has a SHA1 hash of 4fce6e14fd35bdd2ed82b3e534bf196efd2f325a
Anyone else getting this?

**Comment by aardappel** [comment]
Virus checkers sometimes report these things simply because it is an executable they don't see very often, and thus rate the possibility of a match higher.

I run Windows Defender, and never had it complain about PT.. and I created the above installer.

**Comment by hkclark** [comment]
Sounds good... I figured that was the case, but I thought it was better to check just in case others saw it. :-) Thanks and sorry for the false alarm. 

And thanks for the great and very useful tool!
