### ISSUE TITLE
Feature Request: Show idle time in the UI

### ISSUE THREAD

**Issue by danijeldomazet** [aardappel/procrastitracker#58]
Would it be possible to show idle time in the UI?

**Comment by aardappel** [comment]
The problem with idle time is that by default it is 24h - active time, i.e. unless it tries to find a segment of time in which all your active time lies, and only count the time in between, it doesn't know what is idle, and what time you were actually away or asleep. People have different schedules, so you have to account for active periods straddling days etc (currently all timing is on a local 24 hr clock, so even if your work time goes to 1am, it counts 1hr as part of the next day).

**Comment by danijeldomazet** [comment]
I agree it is hard and complicated. 
However, and I am saying this from a user perspective, I would expect the tool to somehow be able to catch the time that I turned the computer on, to track my activity, and to be able to tell me that I've been totaly idle for nearly 2 hours today (because I went out to meet customer). This seems like a normal feature for such a tool.
It is confusing to see that today my computer was turned on 8 hours ago, but when I check the time in procrastitracker I see only 6:15 tracked. It would be great to see that 1:45 tracked somewhere. The fact that procrastitracker must know this time in some way already because i started tracking 8 hours ago, and it shows 6:15 - so where did the time go?? I supposed it was tracked somehow, but it's not in the UI.

I like the idea to try to find a segment of time in which all my active time lies, and only count the time in between. That seems to be exactly what I am looking for?
How would this be implemented? There should maybe be a parameter in minutes, and if idle period would be within this time (say, lower than 120 minutes), than it would be counted as "customer" time or "dentist" time, or whatever, and at the end of the day I would be able to see that I totaly worked 8 hours, not 6:16. 

Sorry about confusing comment. Trying to find a way.

**Comment by aardappel** [comment]
I guess if you turn your computer on and off for a workday, then idle time is more meaningful. Most people don't though.. my computer is always on, and goes to sleep as needed.

Yes, lower than N minutes could be counted as "workday idle time" or whatever. N could default to 0 in the settings to preserve current behavior. Wondering what a good name for this category is, since "customer time" for example is clearly too specific, not everyone has customers :)

Did you try Advanced Settings -> Show Away Dialog When Away For Less Than ? This is that feature, except it is not automatic, you have to indicate what you were doing. I suppose I could add an automatic category as well that doesn't pop up a dialog?

**Comment by aardappel** [comment]
Ok, just added an Advanced Setting that allows you to set a max minutes below which an away period automatically registered as "Away : Other". The away dialog also still works, which then uses "Away : " + name of selected task. You can even use both, if for example you set the auto away to 15 and dialog away to 60, you'll get "Other" for all small breaks, and the bigger ones you get a dialog.

https://github.com/aardappel/procrastitracker/commit/bf6e809fe7d59d8bfb11bc41dcb7f6c2228886ee

**Comment by danijeldomazet** [comment]
OK, that's great. 
I started using the "Show Away Dialog When Away For Less" and it seems to be OK. 

How do I test the new version, where do I download?

**Comment by aardappel** [comment]
Just download as usual, I updated the installer yesterday shortly after my previous post.

**Comment by danijeldomazet** [comment]
I installed it, but I don't see anything new. I all OK with installer? It would be great to add version or date to installer filename.

**Comment by aardappel** [comment]
The About window shows `July 9` for me.

Advanced settings should have `Count "Away : Other" when away less than (Minutes)`.

**Comment by danijeldomazet** [comment]
Please check it this is it: http://strlen.com/procrastitracker/ProcrastiTracker_Setup.exe

**Comment by aardappel** [comment]
Yes, that is it.

**Comment by danijeldomazet** [comment]
It seems like you didn't update it. I just did uninstall, and then download and install. Still old version: Mar 15 2019.

**Comment by aardappel** [comment]
Apologies, just updated again, and the size was indeed different. Must have missed something last time.

**Comment by danijeldomazet** [comment]
OK, installed it, thanks. 
Let me test it for a few days.

**Comment by danijeldomazet** [comment]
Works nicely. Does exactly what I needed. It is now easy to track idle time too. 
Even though this could be done with pop-up (before this fix), it is now much more confortable without pop-up.

Thanks!

**Comment by aardappel** [comment]
That's great to hear :)

**Comment by danijeldomazet** [comment]
Please add the description for this option to the table under http://strlen.com/procrastitracker/#usage.

**Comment by aardappel** [comment]
will do
