### ISSUE TITLE
Windows Defender found Trojan:Win32/Wacatac.D!ml in the installer on the website

### ISSUE THREAD

**Issue by tombuben** [aardappel/procrastitracker#64]
Downloaded the installer from the official website and Windows Defender detected it basically immediately. This is a pretty severe issue. 

I'd recommend hosting the releases on github, since it can be caused by a hacked webhost...

**Comment by aardappel** [comment]
Closing this in favor of existing issue: https://github.com/aardappel/procrastitracker/issues/63

**Comment by aardappel** [comment]
Just looked at adding creating PT installers to the CI, but not working yet.

**Comment by tombuben** [comment]
Setting up SSL on the website where the installer is hosted would make the site itself a bit more trustworthy from the users perspective as well.

**Comment by aardappel** [comment]
@tombuben good point.. looked into https at some point, but my host explicitly doesn't seem to support letsencrypt etc.. I know, I should switch hosts.

**Comment by aardappel** [comment]
You can now also download from github CI: http://strlen.com/procrastitracker/
that may reduce virus warnings for some?
