### ISSUE TITLE
Logged data for browsers (chrome) is no longer correctly categorized by URL

### ISSUE THREAD

**Issue by maritsm** [aardappel/procrastitracker#65]
I have around one year worth of data where all of my time logged in chrome is categorized by URL. The new update i installed today no longer does this, every chrome page is directly under chrome/ in the tree.

I would like to request that this change be reverted, of if it's a bug then it be fixed.
Thanks in advance

**Comment by aardappel** [comment]
This is a change in Chrome, not in Procrastitracker. Chrome never supported getting URLs the way other browsers do (DDE requests), and needs a hack to retrieve it. I can have a look.

What language is your Windows set to? Anything other than english?

**Comment by aardappel** [comment]
Ok, experimented with a new way of getting the URL, and still not working: https://github.com/aardappel/procrastitracker/commit/0cd31414c6e8a672dabc54367cf154fb6cd8c0d7

I'm out of ideas of making this work.

**Comment by maritsm** [comment]
My windows is set to Hungarian currently, could that be an issue?

That said though, the same issue happens with firefox, so I'm going to try and see if changing the system language to English could help

**Comment by maritsm** [comment]
I changed the system language to English/US, the problem is still up.

The problem initially started for me when I decided I would switch to firefox, and when i noticed that the url thing didn't work with it i switched back to chrome, but by then chrome didn't work either. This leads me to suspect that maybe the program is not correctly identifying which method it should use...

**Comment by aardappel** [comment]
Yup, it's broken for me too (in English).

**Comment by maritsm** [comment]
I tried to install an older version of Procrastitracker now to see if the original URL getting thing works or not, but now it won't even load databases anymore, citing that the database was made in a newer version (even for databases that are more than a year old). Even reinstalling the latest commit doesn't fix this

**Comment by aardappel** [comment]
That part is normal: when new features are added that add things stored in the the database, the file format changes. It still knows how to load older versions, but it always writes the newer version. So you can't read newer databases with older versions of PT.

**Comment by maritsm** [comment]
I expected that, yes, the problem is that the new version can't load them now either

**Comment by aardappel** [comment]
The newest version should be able to load any database version, unless it was corrupted for another reason. Does it say anything in particular?

**Comment by maritsm** [comment]
It's just a messagebox with "PT: Trying to load db from newer version"

**Comment by aardappel** [comment]
Then are you aren't using the newest version?

**Comment by maritsm** [comment]
Okay, I see what was wrong last time. I got the newest version off github, used NSIS to make the installer, installed PT using it, but for some reason it didn't create the procrastitracker.exe file. Which meant that when I installed the new version to the same folder where the old version was, it didn't update the procrastitracker.exe file.
I tried the same installation process with 2 different older commits from here, the same issue persisted.

Using the official installer from the website (strlen.com) did work though, and getting the installer off github also worked, so something must've been broken on my end with the installation process.

Although the url problem still persists

**Comment by aardappel** [comment]
yes, I don't have a fix for that at the moment

**Comment by aardappel** [comment]
@maritsm this should now work again if you get the latest version :)

**Comment by maritsm** [comment]
Yes, it works here too (on chrome), thank you very much :)
