### ISSUE TITLE
Missing Wireless SSID when running

### ISSUE THREAD

**Issue by fikrimi23** [aardappel/procrastitracker#66]
I got this weird behaviour when running procrastitracker, it makes my Wifi SSID list missing, I also have tried to isolate the problem  with stopping process and services.
Here is normal looking, with nothing in hidden tray
![image](https://user-images.githubusercontent.com/8409391/98439294-8abac500-2123-11eb-82e3-51037f45a0e0.png)

and here is with procrastitracker running
![image](https://user-images.githubusercontent.com/8409391/98439187-b4bfb780-2122-11eb-94d0-c5c1db99d5f8.png)

**My windows version**
Microsoft Windows 10
Version 20H2 (OS Build 19042.610)

**Processes and services, (csv file)**
[process.txt](https://github.com/aardappel/procrastitracker/files/5504619/process.txt)
[services.txt](https://github.com/aardappel/procrastitracker/files/5504634/services.txt)

**Comment by aardappel** [comment]
PT doesn't do anything networking related at all, so I have no idea how it could possibly affect Wifi.

**Comment by fikrimi23** [comment]
Yep, thought so, thanks for the reply tho, I'll let you know if maybe I found something
