### ISSUE TITLE
Mismatching Data of sub process Total time and Main processes time

### ISSUE THREAD

**Issue by NaisargC** [aardappel/procrastitracker#75]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/51506375/112485712-3ac25f00-8da1-11eb-8e91-42727328400f.png)
 
 In attached report, time for mstsc is 30:55 but its sub process have only 22:50. Similar for acrod32, total time of all sub process is 01:29:05, but the time of main process is 01:37:00. The additional time for mstsc and acrod32 is 08:05. What is the significance of additional time showing up only in Main process?

**Comment by aardappel** [comment]
If a window shows the title `A` for 1 minute and then `A - B` for 1 minute, you'll get a parent `A` with 2 and a child `B` with 1.

In addition, if there was an `A - C` for less time than the "Cull on load" advanced setting, then on next load `C` will be gone, and its time only represent by `A`.
