### ISSUE TITLE
Could you add an autostart function to the app

### ISSUE THREAD

**Issue by InfinityShu** [aardappel/procrastitracker#80]
I have used Procrasti Tracker for a month and it is incredible! So much thanks for your work! For me, I often forget to turn on the app when I turn on my laptop, especially when I wake up at around 3 to study. So I think it would be nice if the program supports an autostart. Thanks for considering my request!

**Comment by aardappel** [comment]
If you use the installer, it installs it in such a way that it automatically starts it on startup.

**Comment by InfinityShu** [comment]
Thanks for your reply! I reinstall the app and it can autostart now. Also, is there a way to know the total time of each tag? From the bar graph I can know how my time is approximately distributed, still I want to know how much time exactly I have spent on each category. Thank you for taking the time to read my comment!

**Comment by aardappel** [comment]
sadly that is not visible, no..
