### ISSUE TITLE
All time no longer rendering right hand side in newer builds

### ISSUE THREAD

**Issue by stickynoteme** [aardappel/procrastitracker#82]
Hi, just updated from a version from around 2019 to the current build from 09/01/21 and noticed that when the quickview is set to all time the right hand overview lines no longer rendered.
![2021-09-04_084612](https://user-images.githubusercontent.com/43216581/132100451-da2f30ec-9223-40b5-b91a-5157826f3103.jpg)

**Comment by aardappel** [comment]
Just checked, but I don't have that problem locally, with `All Time`, or the date range you have, or any other setting.

Does this problem happen for you only with `All Time` or also other settings? Can you experiment?

**Comment by stickynoteme** [comment]
Like most things after playing around with setting for an hour with no results it turned out re-booting the computer solved the issue. XP
