### ISSUE TITLE
feature requests - being able to delete activity, select multiple activities, set the start of the day time

### ISSUE THREAD

**Issue by joemama06** [aardappel/procrastitracker#87]
is it possible to 
select multiple activities, press delete and it's deleted

and also change the start of the day other than 12:00am

I know you can ctrl+h but that's not enough
and ctrl+c, make it 0 but that takes way too much time to do

that's a lovely program tho I'll still use it 
but having these options would make the program literally perfect

**Comment by aardappel** [comment]
There's no multi-select for anything..

Different starting time would be nice, I agree :)

**Comment by joemama06** [comment]
well is it possible?
or does these take ungodly amounts of time

**Comment by aardappel** [comment]
Of course it is possible.. but this is one of the many side projects of mine, so I wouldn't expect any requests to get implemented the moment they're asked for.. or at all.

**Comment by joemama06** [comment]
yeah of course I'm not like "do it now!"
I hope these features are worth adding

I hope at least being able to change the start of the day is worth adding

I look how much I use youtube in the day
but of course I go to sleep past 12am
and so the stats mix up

**Comment by aardappel** [comment]
Had a look, and the day start functionality wasn't very hard, added it here: https://github.com/aardappel/procrastitracker/commit/e116582cf63ae2b64bd0d5be91f6fe6f8973df09

You can now find a setting for it in the advanced preferences.

**Comment by joemama06** [comment]
oh shoot that was fast tysm

btw I made a macro for my mouse button
it does crtl+c,0,enter
it's basically like a delete button
