### ISSUE TITLE
PT recorded Chrome's activity as Explorer's

### ISSUE THREAD

**Issue by InfinityShu** [aardappel/procrastitracker#88]
![image](https://user-images.githubusercontent.com/31622007/148484185-47e679d4-8f4f-4c6b-88cc-3cfa07ce8179.png)
PT appeared to record the same tab under either Chrome or Explorer.  
I did some tests and found out that if I had opened Chrome on my second screen, it would be recorded under Explorer.
However, it was not always the case. Sometimes the Chrome tabs I had opened on my main screen were also recorded under Explorer.
Could you check what might cause this problem? Thank you!

**Comment by aardappel** [comment]
What version of Windows are you on?

**Comment by aardappel** [comment]
Hmm, I bet the problem lies in this code: https://github.com/aardappel/procrastitracker/blob/e116582cf63ae2b64bd0d5be91f6fe6f8973df09/src/timercallback.h#L81-L86

That means Chrome must be spawning an Explorer child window somehow. And probably only on a dual monitor system, because I've not seen this myself.

**Comment by InfinityShu** [comment]
I'm currently on Windows 10, version 21H2. 
Are there possible solutions to this problem? 
I've checked the record and this problem seemed to appear since Dec 29. However, I've been using dual monitor since the first day using PT. I'm thinking that would the causation be an update of Chrome, or an update of the extensions I installed?

**Comment by aardappel** [comment]
Ok, I just reworked the way it obtains the executable name to be more conservative, which hopefully should solve the problem: https://github.com/aardappel/procrastitracker/commit/22ae536c81d5e89470052a5d46ebca6f213c914d

Let me know if that fixes it for you!

**Comment by InfinityShu** [comment]
My laptop has been running for eight hours after I installed the newest version. The problem is thoroghly fixed! Thank you so much!
