### ISSUE TITLE
? Import

### ISSUE THREAD

**Issue by AlennGK** [aardappel/procrastitracker#9]
Is it possible to import data from similar software? 
I would love to convert my **ManicTime** database to PT. Thank you.

**Comment by aardappel** [comment]
There' s currently no import functionality from other software. I have no idea what format ManicTime uses, but such conversions are typically not trivial.

**Comment by AlennGK** [comment]
It is *.cvs.
Also I've noticed that when I watching vieos PT takes that like AFK activity.

**Comment by aardappel** [comment]
Yes, if there's no input for 3 or so minutes it will stop tracking, since you may have walked away from your computer. You can chance this setting.

**Comment by AlennGK** [comment]
I can, but changing setings everytime I watch film is sad, thank you for your help enyway =)
