### ISSUE TITLE
Reusing images is buggy

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/procrastitracker#92]
I could not find a way to reuse an image and be able to resize it without resizing the original, and while trying to circumvent that by putting the copied image into a smaller grid, I get weird bugs like 
![image](https://user-images.githubusercontent.com/70374466/164453610-dfdcbc1e-9ee2-4e44-9ce9-5cedd268a7af.png)
this one (achieved by reusing an image in a subgrid and repeatedly decreasing the text size of the grid with the image until it collapses into pixel size, and then zooming into this).

Additionally, pressing escape to get up a grid level in this view resets the zoom up to the main level, while the selection remains on the same grid as prior to pressing escape.

**Comment by AntonBogun** [comment]
Ok, the worst bug I've found so far is that if there is a tree of collapsed (pixel size) subgrids, entering into one collapsed subgrid actually descends by 2 layers rather than 1.

**Comment by aardappel** [comment]
So first, yes, images are shared, for good reason, so you can use them many times in a document without bloating the file. Making 2 copies at different sizes should be easy by simply loading/dragging in a second copy.

And yes, images also disappear at minified text size.

As for your other issues, you'll need to be clearer as to what steps you're going thru, what you were expecting to see and what instead you see. Maybe based on the tutorial file so I can follow along.

**Comment by AntonBogun** [comment]
> So first, yes, images are shared, for good reason, so you can use them many times in a document without bloating the file. 
Making 2 copies at different sizes should be easy by simply loading/dragging in a second copy.

Is there some place where all the loaded pictures are listed and from where more copies of the same picture can be loaded? I was doing this by copying the cell with the picture, but this seems to link the two and thus make changing the scale individually impossible.

**Comment by aardappel** [comment]
There is no such list. You create a second copy simply by using the `Add Image` menu option, or drag & drop.

**Comment by AntonBogun** [comment]
Does this copy the image again in the file or does it know that it's simply a copy and therefore avoids extra memory usage?

**Comment by aardappel** [comment]
It will make an entirely new copy.

If by "resize" above you meant using the `Scale Image (resample pixels)` option, this will change the image, so they have to be copies if you want to see two different sizes. Resampling affects all uses of an image.

Instead you can also use `Scale Image (display only)`, which works on a shared image, and multiple uses have different sizes. This of course has the disadvantage that large images scaled down for display still use as much memory as the 100% version.

**Comment by AntonBogun** [comment]
By resize I mean the display scale, I couldn't get the scale to work without it sharing across all instances of the image

**Comment by aardappel** [comment]
You are correct, I had somehow assumed display scale was on a per cell basis, but it is per image.

That should indeed be fixed.. looking at the code though, that is not entirely a trivial change.

For now, if you need 2 sizes of an image, I'd recommend loading in a second copy and using `Scale Image (resample pixels)` on it.

**Comment by aardappel** [comment]
sure, maybe make that it's own issue

**Comment by AntonBogun** [comment]
Oh my, I did not see this was the wrong github page, I should probably close my issues and post them at TreeSheets

**Comment by aardappel** [comment]
Hah I didn't either, since I run both projects.

Yes, open one at TreeSheets, but link to this one for context.
