### ISSUE TITLE
Feature Request: Manually Combine Duplicate Programs

### ISSUE THREAD

**Issue by garvage** [aardappel/procrastitracker#98]
i am begging for some way to combine programs that duplicate due to a change in title. [here is my specific issue](https://i.gyazo.com/4c4ab9b50dc29599765a59eb250002ed.png)

**Comment by aardappel** [comment]
Check the keyboard shortcuts on https://strlen.com/procrastitracker/, in particular CTRL+M and CTRL+P sound like they may be useful to you.

**Comment by garvage** [comment]
thanks a lot i saw that page but hadn't noticed that part
